In [4]:
import numpy as np
import pandas as pd

In [5]:
data= { 
    'date' : pd.date_range('2023-12-1' , periods=8)
}
pd.DataFrame(data)

        date
0 2023-12-01
1 2023-12-02
2 2023-12-03
3 2023-12-04
4 2023-12-05
5 2023-12-06
6 2023-12-07
7 2023-12-08

In [6]:
df = pd.DataFrame(data)
pd.index = range(1, len(df) + 1)

In [7]:
df

        date
0 2023-12-01
1 2023-12-02
2 2023-12-03
3 2023-12-04
4 2023-12-05
5 2023-12-06
6 2023-12-07
7 2023-12-08

In [8]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [9]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [10]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64